Modified fs and switch mode scripts

diff --git a/scripts/switch-to-operation-mode b/scripts/switch-to-operation-mode
--- a/scripts/switch-to-operation-mode
+++ b/scripts/switch-to-operation-mode
@@ -2,10 +2,12 @@
 
 echo "Switching to operation mode..."
 
+set -e
+
 current_device=$(mount | grep "on / " | cut -f 1 -d ' ' | grep -o "mmcblk[0-1]")
 number_of_partitions=$(ls /sys/block/$current_device/ | grep -o "${current_device}p[0-3]" | wc -l)
 if [ "$number_of_partitions" != "3" ]; then
-    echo "Must have 3 partitions"
+    echo "Must have 3 partitions. Switching failed"
     exit 1
 fi
 
@@ -13,25 +15,24 @@ if [ ! -w / ]; then
     waggle-fs-unlock
 fi
 
-password=$(readlink /etc/shadow | grep aot | wc -l)
-if [ "$password" != "1" ]; then
-    echo "Password unlocked. Locking..."
-    waggle-pw-lock
-    if [ $? -ne 0 ]; then
-        echo "Lock password failed, PLEASE LOCK THE PASSWORD MANUALLY"
-        exit 1
-    fi
-fi
-
 echo "wellness" > /etc/waggle/hbmode
 systemctl restart waggle-heartbeat.service
+
+waggle-pw-lock
+password=$(readlink /etc/shadow | grep aot | wc -l)
+if [ "$password" != "1" ]; then
+    echo "Password lock failed. Switching failed"
+    exit 1
+fi
+
+waggle-fs-unlock
 systemctl set-default waggle-platform.target
 waggle-fs-lock
 if [ $? -ne 0 ]; then
-    echo "Lock filesystem failed, PLEASE LOCK THE SYSTEM MANUALLY"
+    echo "Locking filesystem failed, Switching failed"
     systemctl set-default waggle-core.target
     exit 1
 fi
 systemctl isolate waggle-platform.target
 
-echo "Done"
+echo "Switching to operation mode...Done"
diff --git a/scripts/switch-to-safe-mode b/scripts/switch-to-safe-mode
--- a/scripts/switch-to-safe-mode
+++ b/scripts/switch-to-safe-mode
@@ -2,21 +2,9 @@
 
 echo "Switching to safe mode..."
 
-# Stop platform services
-systemctl stop $(systemctl show -p Wants waggle-platform.target | cut -d '=' -f 2)
-if [ $? -ne 0 ]; then
-    echo "Failed to stop waggle-platform services"
-    exit 1
-fi
-
-# hbmode to always
-if [ ! -w / ] ; then
-    waggle-fs-unlock
-    echo "always" > /etc/waggle/hbmode
-    waggle-fs-lock
+waggle-fs-unlock
+if [ $? -eq 0 ]; then
+    echo "Switching to safe mode...Done"
+    exit 0
 else
-    echo "always" > /etc/waggle/hbmode
-fi
-systemctl restart waggle-heartbeat.service
-
-echo "Done"
+    echo "Switching to safe mode...Failed"
diff --git a/scripts/waggle-fs-unlock b/scripts/waggle-fs-unlock
--- a/scripts/waggle-fs-unlock
+++ b/scripts/waggle-fs-unlock
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Stop platform services
+systemctl stop -- $(systemctl show -p Wants waggle-platform.target | cut -d '=' -f 2)
+if [ $? -ne 0 ]; then
+    echo "Failed to stop waggle-platform services. Unlocking failed"
+    exit 1
+fi
+
 mount -o remount,rw /
 if [ $? -ne 0 ] ; then
   echo "Mounting / as rw failed"
@@ -15,5 +22,8 @@ if [ $(cat /etc/fstab | grep ' \/ ' | grep 'rw,' | wc -l) -eq 0 ] ; then
   echo "waggle-fs-unlock failed"
   exit 1
 fi
+
+systemctl default waggle-core.target
+rm -f /root/fs_locked
 
 echo "waggle-fs-unlock is done"
