slight cleanup

diff --git a/scripts/waggle_set_mode b/scripts/waggle_set_mode
--- a/scripts/waggle_set_mode
+++ b/scripts/waggle_set_mode
@@ -6,6 +6,16 @@ matches() {
     echo $mode | grep -q $1
 }
 
+if ! matches '^[LU][LU][LU][CP]$'; then
+    echo 'invalid mode. mode must match [LU][LU][LU][CP].'
+    exit 1
+fi
+
+if matches $(waggle_get_mode); then
+    echo 'already in correct mode. no actions will be taken.'
+    exit 0
+fi
+
 failsafe() {
     if [ $? -eq 0 ]; then
         return
@@ -19,16 +29,6 @@ failsafe() {
     waggle-console-lock
     waggle-fs-lock
 }
-
-if ! matches '^[LU][LU][LU][CP]$'; then
-    echo 'invalid mode. mode must match [LU][LU][LU][CP].'
-    exit 1
-fi
-
-if matches $(waggle_get_mode); then
-    echo 'already in correct mode. no actions will be taken.'
-    exit 0
-fi
 
 trap failsafe EXIT
 
